### ISSUE TITLE
Please create new release of oidc-rp, the current release v0.7.1 doesn't include latest fix for Logout

### ISSUE THREAD

**Issue by smalinin** [solid/oidc-rp#15]

**Comment by kjetilk** [comment]
OK, we should make a new release urgently, given that the package-lock also fixes a lot of upstream bugs... @RubenVerborgh , @justinwb : Are you OK with a release now? minor or patch level?

**Comment by RubenVerborgh** [comment]
@smalinin Just to let you know that this was on purpose; we first wanted to move the repository with the same functionality.

@kjetilk New functionality, so minor.

**Comment by kjetilk** [comment]
OK, I'll roll.

**Comment by kjetilk** [comment]
0.8.0 is up now.

**Comment by kjetilk** [comment]
Yes, I did that in solid-auth-oidc, are there others?

**Comment by RubenVerborgh** [comment]
> 0.8.0 is up now.

Where?

> Yes, I did that in solid-auth-oidc, are there others?

solid-auth-client uses it, but I don't think it needs this particular fix.

**Comment by kjetilk** [comment]
>>    0.8.0 is up now.
>
> Where?

On npm...

> solid-auth-client uses it, but I don't think it needs this particular fix.

OK, good. 0.8.0 also updates for vulnerabilities in libs, so I don't know if there is a best practice to update version deps to reflect that?

**Comment by RubenVerborgh** [comment]
> On npm...

Ah, I swear it wasn't there for me when I posted that.

> OK, good. 0.8.0 also updates for vulnerabilities in libs, so I don't know if there is a best practice to update version deps to reflect that?

Yes.
