### ISSUE TITLE
text-encoding@0.6.4 no longer maintained

### ISSUE THREAD

**Issue by tuelsch** [solid/oidc-rp#23]
I don't know how critical this issue is, but yarn (and possibly npm) is giving a warning when installing solid-auth-client which depends on oidc-rp.

![image](https://user-images.githubusercontent.com/1659006/47965661-3c7a1380-e07c-11e8-83da-a046efd82043.png)

**Comment by dmitrizagidulin** [comment]
Fixed in PR #28, closing.
