### ISSUE TITLE
relies on archived project @trust/webcrypto

### ISSUE THREAD

**Issue by jonassmedegaard** [solid/oidc-rp#26]
This project depends on https://github.com/anvilresearch/webcrypto which is marked as archived, with a note in README.md that the authors strongly recommend against using it directly, and instead encourages creating a fork.

**Comment by dmitrizagidulin** [comment]
@jonassmedegaard Yeah, there's currently discussion on where the best place to host a definitive fork should be. If the Solid project is interested, we can fork it here. Plus I know there's other communities that are interested in taking it up.

**Comment by dmitrizagidulin** [comment]
@jonassmedegaard I started up an issue to track the discussion of where `webcrypto` should be maintained here: https://github.com/solid/cryptography-and-security/issues/1

**Comment by dmitrizagidulin** [comment]
Fixed in PR #28, merging.
